import { promises as fs } from 'node:fs';
import path from 'node:path';

type LegacyWord = {
  english: string;
  welsh: string;
  type: string;
};

type LegacyPayload = { words: LegacyWord[] };

type WordInsert = {
  english: string;
  welsh: string;
  legacy_type: string;
  part_of_speech: string;
  frequency_rank: number | null;
  notes: string | null;
};

const ROOT = process.cwd();
const INPUT_PATH = path.join(ROOT, 'data.json');
const OUTPUT_JSON_PATH = path.join(ROOT, 'supabase/seed/legacy-words.json');
const OUTPUT_SQL_PATH = path.join(ROOT, 'supabase/seed/legacy-seed.sql');

const PART_OF_SPEECH_MAP: Record<string, string> = {
  nouns: 'noun',
  adjectives: 'adjective',
  verb_infinitives: 'verb_infinitive',
  preterite_conjugations: 'conjugation',
  present_tense_conjugations: 'conjugation',
  whole_phrases: 'phrase',
  time_expressions: 'phrase',
};

function escapeSql(value: string): string {
  return value.replaceAll("'", "''");
}

async function main() {
  const raw = await fs.readFile(INPUT_PATH, 'utf-8');
  const payload = JSON.parse(raw) as LegacyPayload;

  const words: WordInsert[] = payload.words.map((word) => ({
    english: word.english.trim(),
    welsh: word.welsh.trim(),
    legacy_type: word.type,
    part_of_speech: PART_OF_SPEECH_MAP[word.type] ?? 'phrase',
    frequency_rank: null,
    notes: null,
  }));

  const categorySet = new Set(words.map((word) => word.legacy_type));

  const seedSqlLines = [
    '-- Generated by scripts/migrate-legacy-json.ts',
    'begin;',
    ...Array.from(categorySet).map(
      (category) =>
        `insert into public.categories (name) values ('${escapeSql(category)}') on conflict (name) do nothing;`,
    ),
    ...words.map(
      (word) =>
        `with inserted as (\n` +
        `  insert into public.words (welsh, english, part_of_speech, frequency_rank, legacy_type, notes)\n` +
        `  values ('${escapeSql(word.welsh)}', '${escapeSql(word.english)}', '${escapeSql(word.part_of_speech)}', null, '${escapeSql(word.legacy_type)}', null)\n` +
        `  returning id, legacy_type\n` +
        `)\n` +
        `insert into public.word_categories (word_id, category_id)\n` +
        `select inserted.id, c.id from inserted join public.categories c on c.name = inserted.legacy_type\n` +
        `on conflict do nothing;`,
    ),
    'commit;',
    '',
  ];

  await fs.writeFile(OUTPUT_JSON_PATH, JSON.stringify({ words }, null, 2));
  await fs.writeFile(OUTPUT_SQL_PATH, seedSqlLines.join('\n'));

  console.log(`Converted ${words.length} words from legacy JSON.`);
  console.log(`Wrote: ${path.relative(ROOT, OUTPUT_JSON_PATH)}`);
  console.log(`Wrote: ${path.relative(ROOT, OUTPUT_SQL_PATH)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
