alter table public.user_card_state
  add column if not exists in_stack boolean not null default false;

alter table public.user_stats
  add column if not exists category_progress jsonb not null default '{"ADJ":{"learned":0,"reviewed":0},"NOUN":{"learned":0,"reviewed":0},"VERB":{"learned":0,"reviewed":0}}'::jsonb;

create table if not exists public.translation_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  word_id bigint not null references public.lexicon(id) on delete cascade,
  welsh_lc text not null,
  english_1 text not null,
  theme text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.translation_feedback enable row level security;
